### ISSUE TITLE
ClassNotFoundException

### ISSUE THREAD

**Issue by Nolane** [AnderWeb/discreteSeekBar#38]
What I've done: added jcenter() to repositories and added compile 'org.adw.library:discrete-seekbar:1.0.0' to dependencies. 

07-15 02:23:20.401  29558-29558/com.author.name E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.author.name/com.author.name.ui.CreateStackActivity}: android.view.InflateException: Binary XML file line #23: Error inflating class com.adw.library.widgets.discreteseekbar.DiscreteSeekBar
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2325)
...
     Caused by: android.view.InflateException: Binary XML file line #23: Error inflating class com.adw.library.widgets.discreteseekbar.DiscreteSeekBar
            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:757)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
            at com.author.name.ui.CreateStackFragment.onCreateView(CreateStackFragment.java:46)
            at android.app.Fragment.performCreateView(Fragment.java:2053)
...
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.adw.library.widgets.discreteseekbar.DiscreteSeekBar" on path: DexPathList[[zip file "/data/app/com.author.name-1/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
            at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
...
    Suppressed: java.lang.ClassNotFoundException: com.adw.library.widgets.discreteseekbar.DiscreteSeekBar
            at java.lang.Class.classForName(Native Method)
            at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
            at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
            ... 25 more
     Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available

**Comment by AnderWeb** [comment]
Seems you are using "com.adw.library.widgets.discreteseekbar.DiscreteSeekBar" in your layout XML, but you should use "org.adw.library.widgets.discreteseekbar.DiscreteSeekBar".

Please confirm, thanks.

**Comment by Nolane** [comment]
Thanks, you helped me. Can't understand why I used _com_...
