### ISSUE TITLE
Can't make the onScrollChangeListener is it broken ?

### ISSUE THREAD

**Issue by y11t** [AnderWeb/discreteSeekBar#51]
Hi there,

I cant attach the listener to seekbar. How can i do it? I wanna change a textview to display the new seekbar value. My code is:

        DiscreteSeekBar seekBar = (DiscreteSeekBar)rootView.findViewById(R.id.seekBar);
        seekBar.setOnScrollChangeListener(new View.OnScrollChangeListener() {
            @Override
            public void onScrollChange(View v, int scrollX, int scrollY, int oldScrollX, int oldScrollY) {
                tvRange.setText("New value is "+scrollY);
            }
        });

And the error is : 

4336-4336/com.developement.mt.langapp E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.developement.mt.langapp, PID: 4336
    java.lang.NoClassDefFoundError: com.developement.mt.langapp.SearchFragment$1
            at com.developement.mt.langapp.SearchFragment.onCreateView(SearchFragment.java:37)
            at android.support.v4.app.Fragment.performCreateView(Fragment.java:1962)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1026)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1207)
            at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:738)
            at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1572)
            at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:493)
            at android.os.Handler.handleCallback(Handler.java:808)
            at android.os.Handler.dispatchMessage(Handler.java:103)
            at android.os.Looper.loop(Looper.java:193)
            at android.app.ActivityThread.main(ActivityThread.java:5292)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:824)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:640)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by y11t** [comment]
Nevermind used setOnProgressChangeListener it works fine.
